// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /disable_code)
	DisableCode(ctx echo.Context) error

	// (POST /enable_code)
	EnableCode(ctx echo.Context) error

	// (GET /info)
	GetInfo(ctx echo.Context) error

	// (POST /light)
	Light(ctx echo.Context) error

	// (GET /read)
	ReadPayload(ctx echo.Context) error

	// (GET /test)
	GetTest(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DisableCode converts echo context to params.
func (w *ServerInterfaceWrapper) DisableCode(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DisableCode(ctx)
	return err
}

// EnableCode converts echo context to params.
func (w *ServerInterfaceWrapper) EnableCode(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.EnableCode(ctx)
	return err
}

// GetInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetInfo(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetInfo(ctx)
	return err
}

// Light converts echo context to params.
func (w *ServerInterfaceWrapper) Light(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Light(ctx)
	return err
}

// ReadPayload converts echo context to params.
func (w *ServerInterfaceWrapper) ReadPayload(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ReadPayload(ctx)
	return err
}

// GetTest converts echo context to params.
func (w *ServerInterfaceWrapper) GetTest(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetTest(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/disable_code", wrapper.DisableCode)
	router.POST(baseURL+"/enable_code", wrapper.EnableCode)
	router.GET(baseURL+"/info", wrapper.GetInfo)
	router.POST(baseURL+"/light", wrapper.Light)
	router.GET(baseURL+"/read", wrapper.ReadPayload)
	router.GET(baseURL+"/test", wrapper.GetTest)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RWUW/jNgz+KwK3Ry92ku3a89v1NhyKbdit3VsRBKrFxDo4kk6i2wUH//dBku04tZN1",
	"a4dtb7ZIfSI/fiL1BQq9M1qhIgf5F7DojFYOw48jTrXrlvxKoRWhIv/JjalkwUlqlX5yWoUNRYk77r++",
	"triBHL5KD/BptLo0wkLTNAkIdIWVxqNA3h7Idugc3yJ7lFSydq3QAhlXojOC390ixsgErmlvQpjHqKjq",
	"XcTiD1xW/L7CCOfdHSTBAfI7QK7mS//P1SUk8NlCArUpOCTAqwpWCeDvfGcq9KCtbzwSHFmpttAkYJEL",
	"H4Ox2qAlGak0fF/paDgOjkpkrZFRyYn5BVdwpdCygDU89e3FZbbI5suLt28W48ObfkXff8KCIFAUoNZS",
	"bfQ4rJJb8cgtrh/QOhmLeBxf58E6j2E481mWTXGw0wKrMZaxWtQFsWgeAn34+c13U0BObyjEJzhNVLYz",
	"s2AeAi6yRZYts/lZ0JNJ97gnkp4/k/so9BHrXnzjQ28PQocENtruOEEOUtFyUGupCLdoA8vtTTiF1Nmn",
	"YrX4uZYWhZd9e2LnvprK5FFSUa61oXPXq5LbkpgOhqN7pfydgwSEdO2XI/HkPnU+41gdFrWVtL/1tz0y",
	"eMWdLN7VVPZdx++596sHiJLIxC7Tif848CtuferprzffvPft4La9dV6M7N3Ha48kaajPXjCQzeazzDOj",
	"DSpuJOSwnGUzLwzDqQxBpm26667eRrvAn9dCaJzXAnL4Pnq9j1XwhUFHV1rs/1LDHSus74bnevHBcULB",
	"4wbdZsS28gHVoYnGvjeYHIssO3Vy75c+GS9NAt/+nW0hzDTq50+o/kH9b5iO+fwHie7u0hYnesENUm0V",
	"80MjDOunjdQxvRlOOEieVOgD0rU/YDrN13l+DCfiBPO3dVGgc5u6qvbMhoRQsOj9IuZCezwtzp+C+bV0",
	"6WJ5zhJxaOrPkqRD6lr8pi/gvy/I7sF1RpCO8fCWal+RG0LLtJepY/eIqk1GjNR4g1x8bF9u/6AiQwbP",
	"VmKfyAt5I4wqPMvbLz9OXdHf/NbXKHwMpRvwkN8djfa7VbPyVuu7RzDWtmoHe56mlS54VWpH+WV2kUGz",
	"av4IAAD//+ib977ODAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
